//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFImageScraping.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_TAG
    {
        public MST_TAG()
        {
            this.TR_IMG = new HashSet<TR_IMG>();
        }
    
        public int TAG_ID { get; set; }
        public string TAG_NM { get; set; }
    
        public virtual ICollection<TR_IMG> TR_IMG { get; set; }
    }
}
