//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFImageScraping.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_WEBSITE
    {
        public MST_WEBSITE()
        {
            this.MST_RSS = new HashSet<MST_RSS>();
            this.MST_SHAKEHAND = new HashSet<MST_SHAKEHAND>();
            this.TR_DOWNLOAD_PATH = new HashSet<TR_DOWNLOAD_PATH>();
        }
    
        public int WEBSITE_ID { get; set; }
        public string WEBSITE_NM { get; set; }
        public string WEBSITE_URL { get; set; }
        public decimal UPDATE_MIN { get; set; }
        public bool ENABLE_FLG { get; set; }
    
        public virtual ICollection<MST_RSS> MST_RSS { get; set; }
        public virtual ICollection<MST_SHAKEHAND> MST_SHAKEHAND { get; set; }
        public virtual ICollection<TR_DOWNLOAD_PATH> TR_DOWNLOAD_PATH { get; set; }
    }
}
