//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFImageScraping.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScrapingDBEntities : DbContext
    {
        public ScrapingDBEntities()
            : base("name=ScrapingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MST_RSS> MST_RSS { get; set; }
        public virtual DbSet<MST_SHAKEHAND> MST_SHAKEHAND { get; set; }
        public virtual DbSet<MST_TAG> MST_TAG { get; set; }
        public virtual DbSet<MST_WEBSITE> MST_WEBSITE { get; set; }
        public virtual DbSet<TR_DOWNLOAD_PATH> TR_DOWNLOAD_PATH { get; set; }
        public virtual DbSet<TR_IMG> TR_IMG { get; set; }
        public virtual DbSet<TR_PATH> TR_PATH { get; set; }
    }
}
