//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFImageScraping.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_DOWNLOAD_PATH
    {
        public int DOWNLOAD_PATH_ID { get; set; }
        public int WEBSITE_ID { get; set; }
        public string DOWNLOAD_PATH { get; set; }
    
        public virtual MST_WEBSITE MST_WEBSITE { get; set; }
    }
}
