//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFImageScraping.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PATH
    {
        public int PATH_ID { get; set; }
        public int IMG_ID { get; set; }
        public string IMG_PATH { get; set; }
        public int PATH_TYPE { get; set; }
        public bool ENABLE_FLG { get; set; }
    
        public virtual TR_IMG TR_IMG { get; set; }
    }
}
