CREATE TABLE [dbo].[MST_WEBSITE] (
    [WEBSITE_ID]  INT            IDENTITY (1, 1) NOT NULL,
    [WEBSITE_NM]  NVARCHAR (250) NOT NULL,
    [WEBSITE_URL] NVARCHAR (250) NOT NULL,
    [UPDATE_MIN]  NUMERIC (18)   NOT NULL DEFAULT 30,
    [ENABLE_FLG] BIT NOT NULL DEFAULT 1, 
    PRIMARY KEY CLUSTERED ([WEBSITE_ID] ASC)
);

