CREATE TABLE [dbo].[TR_DOWNLOAD_PATH] (
    [DOWNLOAD_PATH_ID] INT            IDENTITY (1, 1) NOT NULL,
	[WEBSITE_ID] INT NOT NULL,
    [DOWNLOAD_PATH]    NVARCHAR (200) NOT NULL,
    PRIMARY KEY CLUSTERED ([DOWNLOAD_PATH_ID] ASC), 
    CONSTRAINT [FK_TR_DOWNLOAD_PATH_ToMST_WEBSITE] FOREIGN KEY ([WEBSITE_ID]) REFERENCES [MST_WEBSITE]([WEBSITE_ID])
);

