CREATE TABLE [dbo].[TR_TAG] (
    [TAG_ID] INT NOT NULL,
    [IMG_ID] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([TAG_ID] ASC, [IMG_ID] ASC), 
    CONSTRAINT [FK_TR_TAG_ToTR_IMG] FOREIGN KEY ([IMG_ID]) REFERENCES [TR_IMG]([IMG_ID]), 
    CONSTRAINT [FK_TR_TAG_ToMST_TAG] FOREIGN KEY ([TAG_ID]) REFERENCES [MST_TAG]([TAG_ID])
);

