CREATE TABLE [dbo].[TR_IMG]
(
	[IMG_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [IMG_NM] NVARCHAR(100) NOT NULL, 
    [WIDTH] INT NULL, 
    [HEIGHT] INT NULL, 
    [HASH] NVARCHAR(50) NULL, 
    [SIZE] INT NOT NULL,
)
