CREATE TABLE [dbo].[MST_SHAKEHAND] (
    [SHAKEHAND_ID]  INT           IDENTITY (1, 1) NOT NULL,
	[WEBSITE_ID] INT NOT NULL,
    [SHAKEHAND_DNS] NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([SHAKEHAND_ID] ASC), 
    CONSTRAINT [FK_MST_SHAKEHAND_ToMST_WEBSITE] FOREIGN KEY ([WEBSITE_ID]) REFERENCES [MST_WEBSITE]([WEBSITE_ID])
);

