CREATE TABLE [dbo].[MST_RSS] (
    [RSS_ID]     INT            IDENTITY (1, 1) NOT NULL,
    [WEBSITE_ID] INT            NULL,
    [RSS_URL]    NVARCHAR (250) NULL,
    PRIMARY KEY CLUSTERED ([RSS_ID] ASC), 
    CONSTRAINT [FK_MST_RSS_ToMST_WEBSITE] FOREIGN KEY ([WEBSITE_ID]) REFERENCES [MST_WEBSITE]([WEBSITE_ID])
);

